import { useState } from 'react';
import { Facts, Note } from './StageParts';
import { EmptyPhase } from './EmptyPhase';
export default function Attribution({ results }) {
  const [selectedId, setSelectedId] = useState('');
  const report = results[4]?.data;
  if (!report) return <EmptyPhase title="Assess the candidate evidence." description="Run AIS correlation before generating the backend attribution report."/>;
  const ranked = report.ranked_candidates || [];
  const candidate = ranked.find(v=>v.mmsi===selectedId) || ranked[0];
  const score = value => Math.max(0,Math.min(100,parseFloat(value)||0));
  return <><div className="analysis-main evidence"><span className="eyebrow">SIMULATED CANDIDATE COMPARISON</span><h3>{ranked.length ? 'Compatibility, not culpability.' : 'No attribution available.'}</h3><p className="muted">Backend scores are not calibrated probabilities.</p>{ranked.map((v,i)=><button className={`candidate-row ${candidate?.mmsi===v.mmsi?'selected':''}`} key={`${v.mmsi}-${i}`} aria-pressed={candidate?.mmsi===v.mmsi} onClick={()=>setSelectedId(v.mmsi)}><span>{String(v.rank).padStart(2,'0')}</span><div><strong>{v.vessel_name}</strong><span className="score-track"><i style={{width:`${score(v.overall_compatibility)}%`}}/></span></div><span>{v.overall_compatibility}</span></button>)}{!ranked.length&&<p>No candidate was supplied for ranking.</p>}<Note>{report.system_disclaimer || 'No candidate can be attributed from the available evidence.'}</Note><Facts items={[["Case ID",report.case_id || 'Not issued'],["Report time",report.timestamp || 'Not provided'],["Ranked candidates",String(ranked.length)],["Verdict summary",report.verdict_summary || "Not returned"],["Regional fleet",String(report.traffic_audit?.total_regional_fleet_scanned ?? "Not returned")],["Corridor candidates",String(report.traffic_audit?.corridor_suspects_isolated ?? "Not returned")],["Legal framework",report.legal_framework || "Not returned"],["Recommended action",report.recommended_action || "Not returned"]]}/></div><aside className="analysis-side"><span className="eyebrow">05 / RETURNED EVIDENCE FACTORS</span><h3>{candidate ? candidate.vessel_name : 'Inconclusive result.'}</h3>{candidate&&<><Facts items={[["Generated MMSI",candidate.mmsi],["Investigation priority",candidate.investigation_priority],["Spatial score",candidate.evidence_breakdown.spatial_proximity_score],["Temporal score",candidate.evidence_breakdown.temporal_match_score],["Cargo factor",candidate.evidence_breakdown.vessel_cargo_risk],["Behavioral score",candidate.evidence_breakdown.behavioral_anomaly_score]]}/><p>{candidate.evidence_breakdown.behavioral_observation}</p></>}<Note>These rankings are based on simulated AIS. The updated stage-4 request model carries generated speed_knots values, but they are not verified vessel observations.</Note><Note>Missing evidence: verified AIS history, discharge observation, chemical sampling and measured environmental forcing. No enforcement conclusion can be drawn from this report.</Note></aside></>;
}
