import { useState } from 'react';
import { ArrowUpRight, MapPin } from 'lucide-react';
import ImageView from './ImageView';
import { coordinateFields } from '../../config/sceneConfig';
import { validateBounds } from '../../services/pipeline';
export default function Detection({ file, bounds, updateBounds, preview, maskURL, results, active }) {
  const [layer,setLayer] = useState('Original SAR');
  return <div className="detection-layout"><section className="coordinate-panel"><div className="section-heading"><div><span className="eyebrow">01 / GEOGRAPHIC REFERENCE</span><h2>Locate your observation.</h2></div><MapPin size={23} strokeWidth={1.3}/></div><p>All six coordinates are optional. Leave any unknown values blank; an image is required to run the investigation.</p><fieldset className="coordinate-grid" disabled={active !== null}><legend className="sr-only">Optional coordinates</legend>{coordinateFields.map(([key,label],i) => <label className="coordinate-box" key={key}><span><b>0{i+1}</b>{label}</span><div><input aria-label={label} type="number" step="any" min={key.includes('lat') ? -90 : -180} max={key.includes('lat') ? 90 : 180} value={bounds[key]} onChange={e=>updateBounds({...bounds,[key]:e.target.value})}/><span>°</span></div><small>{key.includes('lat')?'−90 to 90 · latitude':'−180 to 180 · longitude'}</small></label>)}</fieldset><p className="input-hint">{validateBounds(bounds) || 'Coordinates are optional. Upload an image to run the investigation.'}</p></section><section className="detection-imagery"><div className="toolbar" role="group" aria-label="Image layers">{['Original SAR','Model overlay','Segmentation'].map(name=><button key={name} disabled={!preview || (name !== 'Original SAR' && !maskURL)} aria-pressed={layer===name} onClick={()=>setLayer(name)}>{name}</button>)}</div><ImageView preview={preview} maskURL={maskURL} layer={maskURL?layer:'Original SAR'}/><div className="image-meta"><span>{file ? 'SAR OBSERVATION' : 'NO SCENE SELECTED'}</span><a href="#investigation">Change observation <ArrowUpRight size={12}/></a></div>{results?.[0] && <p className="detection-response">Backend returned a PNG mask · {results[0].size.toLocaleString()} bytes{results[0].responseHeaders?.["x-lat"] ? ` · ${results[0].responseHeaders["x-lat"]}°, ${results[0].responseHeaders["x-lon"]}°` : ""}. Select Segmentation to inspect the exact mask.</p>}</section></div>;
}
